name = "groceryrun-alerts"
main = "index.js"
compatibility_date = "2024-09-01"

kv_namespaces = [
  { binding = "ALERTS_KV", id = "a25ede1dceef46ac973be64e36f41986" }
]

[triggers]
crons = ["0 13 * * *"]  # 9am ET (1pm UTC) daily
